// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Artists: typeof import('./src/components/Artists.vue')['default']
    CarbonClose: typeof import('virtual:vite-icons/carbon/close')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonLogout: typeof import('virtual:vite-icons/carbon/logout')['default']
    CarbonMenu: typeof import('virtual:vite-icons/carbon/menu')['default']
    CarbonShare: typeof import('virtual:vite-icons/carbon/share')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Genres: typeof import('./src/components/Genres.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Mood: typeof import('./src/components/Mood.vue')['default']
    Obscurity: typeof import('./src/components/Obscurity.vue')['default']
    TimeRangeSelector: typeof import('./src/components/TimeRangeSelector.vue')['default']
    Tracks: typeof import('./src/components/Tracks.vue')['default']
  }
}

export { }
