// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Artists: typeof import('./components/Artists.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Genres: typeof import('./components/Genres.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    Mood: typeof import('./components/Mood.vue')['default']
    Obscurity: typeof import('./components/Obscurity.vue')['default']
    TimeRangeSelector: typeof import('./components/TimeRangeSelector.vue')['default']
    Tracks: typeof import('./components/Tracks.vue')['default']
  }
}

export { }
